supervisor/supervisorctl.py

Fix options with missing argument type in usage message

---

docs/configuration.rst

Added undocumented configuration file paths in documentation

---

docs/plugins.rst

Added supervisor_checks to the list of third-party libraries.

Added supervisor_checks to the docs.

---

supervisor/rpcinterface.py

Improved the documentation of the reloadConfig API method

---

docs/running.rst

Document supervisorctl actions

---

supervisor/options.py
supervisor/poller.py

Ensuring proper cleanup for kqueue poller seems to fix https://github.com/Supervisor/supervisor/issues/858

Close pollers during cleanup

---

docs/running.rst
supervisor/supervisorctl.py

help for `update` and `reread` could better as mentioned in https://github.com/Supervisor/supervisor/issues/720

clarify reread and update

---

docs/running.rst

As this commit comment to say, `update` has support argument,  this is a very useful and import function in production environment, so we should update the document. https://github.com/Supervisor/supervisor/commit/66f414e8fce2a5804ce8f4b8d47a4f7f1078f0b9#diff-649301c0f2871eb2b2197664387ae115

Add argument note to update

---

supervisor/rpcinterface.py
supervisor/supervisord.py

Adds a log on the reloadConfig RPC method reporting the
added, changed and removed process groups, and also logs
process groups added and removed.

Add update logs

---

supervisor/datatypes.py

Clear warnings for invalid process/group names

---

supervisor/supervisord.py

Avoid possible race condition between SIGTERM and SIGHUP

---

docs/plugins.rst

Added link to superhooks https://pypi.org/project/superhooks/

Added superhooks to plugin page

---

docs/events.rst

Fix simple typo: notificatons -> notifications

---

supervisor/rpcinterface.py
supervisor/states.py
supervisor/tests/test_rpcinterfaces.py

Add a set of SIGNALABLE_STATES and use this to determine if a signal can be sent to a process.

Enable sending signals to stopping processes

---

docs/plugins.rst

switched from Python 2.7 to Python 3.6

update supvisors description

---

docs/installing.rst

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

Improve the rationale of why distribution packages lag behind

---

supervisor/rpcinterface.py

Add two configuration properties to the getAllConfigInfo method

Add two configuration properties to the getAllConfigInfo method

---

supervisor/options.py
supervisor/tests/test_options.py

Replace os.close with os.closerange

---

docs/plugins.rst

Dear supervisord team. I would like to make a contribution to the 'plugins' list. Please look into our project repository for further details

Adding Polyvisor to plugins list

---

docs/subprocess.rst

1 + 2 + 3 would be total of 6 seconds of wait

chore: typo in docs
