docs/plugins.rst

as it became deprecated in favor of SupervisorPHP

Remove supervisord-php-client from the list

---

docs/introduction.rst

https://github.com/Supervisor/supervisor/blob/master/docs/introduction.rst and http://supervisord.org/introduction.html#overview said that compatibility was [2.4, 3.0) when it should be >2.6 && >3.2.

Compatibility information for Python 3 was out of date

---

setup.py
tox.ini

because it's awesome.
This might be more controversial, since test runners can be a bit of a religion... :smile: 
`py.test` can take a bunch of different arguments so I added `{posargs}` to the `tox.ini` so that options can be passed from a `tox` command to the underlying `py.test`. For example:
```
$ tox -e py27,py34 -- --tb=short --showlocals --durations=5 supervisor/tests/test_supervisorctl.py
GLOB sdist-make: /Users/marca/dev/git-repos/supervisor/setup.py
py27 inst-nodeps: /Users/marca/dev/git-repos/supervisor/.tox/dist/supervisor-4.0.0-dev.zip
py27 runtests: PYTHONHASHSEED='2805401122'
py27 runtests: commands[0] | py.test --tb=short --showlocals --durations=5 supervisor/tests/test_supervisorctl.py
============================================================================= test …
```

tox.ini: Switch to use py.test

---

supervisor/supervisord.py

When I run MongoDB under Supervisor 4.0-dev, MongoDB closes its stdout stream and Supervisor reacts by spinning the CPU at 100%. This patch fixes the problem by unregistering file descriptors that are no longer readable or writable.
(Both MongoDB and Supervisor remained responsive; this bug was really just a pure CPU drain.)

Unregister file descriptors when streams close.

---

supervisor/options.py
supervisor/tests/fixtures/example/included.conf
supervisor/tests/fixtures/include.conf
supervisor/tests/test_options.py

I've been giving some thought and investigation and because of how ConfigParser is implemented (in 2.7 and 3.4) I couldn't come with more elegant solution.
Suggestions are welcome.
I'm using string replace instead of format because the same value can have multiple substitutions, for example: 
xx = %(here)s/%(program_name)s

Attempt to fix %(here)s in included files. Fix #81, related to #84

---

supervisor/options.py
supervisor/supervisord.py
supervisor/tests/base.py

This adds a new parse_infos besides parse_warnings, and uses it for the
'Included extra file "%s" during parsing' info.
Fixes #272

Add `parse_infos` to options, use it for "parsed file" message

---

docs/configuration.rst

typo fix in docs

---

supervisor/medusa/CHANGES.txt
supervisor/medusa/http_server.py

Medusa checked every 500 connections made for connections older
than 30 minutes and closed them. This made it impossible to keep
a persistent connection when many short-lived connections happen at
the same time. It will now only close connections that have been
inactive for that amount of time, i.e. no send/recv activity.
Fixes #650

Improve Medusa zombie connection detection

---

CHANGES.txt

Fix a little typo: `xmlrpxlib` => `xmlrpclib`

Fix xmlrpclib typo

---

docs/running.rst

Supervisor is doing
stop then start
there is no such method as restart in the restart command.

Correct behaviour

---

docs/running.rst
supervisor/options.py
supervisor/supervisorctl.py
supervisor/tests/test_supervisorctl.py
supervisor/xmlrpc.py

New pull request because previous pull request was on my master.
Summary:
- error_status being set in supervisorctl.py raises a SystemExit when in non-interactive mode.
- handle_error wraps all error output and sets error_status.
- onecmd is the entry point for single command and where we enforce SystemExit returning with the error code set in handle_error.
- Updated the docs to reflect that we have non-zero exit codes for failure cases or app status not running.
- Fully tested.
@mnaberez - would love to get this one merged and done. Please let me know if there's anything I can do to get this to a point where you would feel comfortable with it, or if someone else needs to review it. It's the oldest bug in the project now.
Previous pull request ref: #641
Fixes #24

Add LSB Exit codes for non-interactive mode.

---

supervisor/options.py

This adds support for this syntax in an include:
```
[include]
files = /etc/supervisor/supervisor.d/%(host_node_name)s/*.conf
```
This allows me to deploy the same directories to all of my hosts and let supervisor figure out which ones to load by what host it is running on.

expand the host node name option on includes

---

docs/plugins.rst

This adds a link in the docs to [supervisor-alert](https://github.com/rahiel/supervisor-alert).

plugins.rst: add supervisor-alert

---

CHANGES.txt

Changing history is frowned upon, but this change doesn't match what the code actually does (nor does it match the documentation). Since it could be confusing, I think it's definitely worth fixing.

Correct redirect_stderr target in 3.0a1 release note

---

supervisor/loggers.py
supervisor/tests/test_loggers.py

Python 3.5.2 disallows `open('/dev/stdout', 'a')` (it causes OSError with errno=ESPIPE) but allows `open('/dev/stdout', 'w')`. This change makes Supervisor detect this error condition and fix it if possible.
(I might try to get this fixed in Python itself, but this patch helps Supervisor work with existing Python 3 installations.)

Fixed logfile output to special files like /dev/stdout on Python 3.

---

docs/plugins.rst

Supvisors works as a plugin of Supervisor, using the XML-RPC extension.

add Supvisors to the list of tools for multiple Supervisor instances

---

docs/configuration.rst

Child processes will inherit the file descriptor limits, so this amends the documentation to make this absolutely clear, as discussed in #813.

Explicitly document minfds limit inheritance

---

docs/api.rst

There are a couple of pages of docs about using xml-rpc to communicate with supervisor, however on the main demo page `docs/api.rst`, there is nothing about specifying the `rpcinterface`.
So that people in the future don't have to go through the issue I had for a few days of just failing to be able to communicate with the supervisor, I placed the code-block of how to specify the `rpcinterface` directly into the `docs/api.rst` page.

Update documentation regarding xml-rpc communication

---

.gitignore

This adds the `venv` (a common dir for virtual envs) and `.cache` (used by pip while building) directories to `.gitignore`.

Add a couple of common python dirs to .gitignore

---

supervisor/poller.py
supervisor/supervisord.py
supervisor/tests/test_poller.py

I ran into this bug using the web UI on macOS. It seems that https://github.com/Supervisor/supervisor/pull/589 was on the right track but has unnecessarily strict rules to unregister a file descriptor. Only need to check if the writers are not writeable anymore - readers not readable.

Fix 100% CPU usage

---

supervisor/options.py
supervisor/tests/test_options.py

Fix start duplicate supervisord will remove exists pidfile

---

supervisor/options.py
supervisor/tests/test_supervisord.py

As reported in issue #339, changes to an event listener configuration don't get noticed during an "update" call.  This pull request includes a unittest to demostrate the problem along with a fix that causes the unittest to pass.
Note, this fix only ensures that the changes trigger as part of diff_to_activate.  I have not check to see if there are any side-effects associated with doing this for eventlisteners.

Config reloading now detects changes to event listeners.  Fixes #339

---

.travis.yml
tox.ini

Look for syntax errors or undefined names in both Python 2 and Python 3.

 Run a handful of key flake8 tests on all new PRs 

---

docs/plugins.rst

I have written a centralized web interface to help manage multiple supervisor instances.
I think it might be useful for other people.
The aim of this PR is to add it to the list of supervisor plugins

Add multivisor to the list of dashboard plugins

---

docs/api.rst

The example of [getProcessInfo()](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getProcessInfo) shows wrong state code for "RUNNING". It should be 20 as described in [Process States](http://supervisord.org/subprocess.html#process-states).
After a quick grep, I think this is the only mistake about process states.

Fix process state code in docs

---

.travis.yml
tox.ini

Python 3.7 on Travis CI configured in alignment with travis-ci/travis-ci#9069

Travis CI and Tox: Add Python 3.7 to the testing

---

docs/installing.rst

Today, `pip` has replaced `easy_install` to install python packages.
This PR updates documentation and fixes issue #623

Replace easy_install by pip installation method

---

docs/glossary.rst
docs/installing.rst
docs/plugins.rst

This PR updates the protocol, domain and add a trailing slash to the URLs.

Update pypi.python.org URLs to pypi.org

---

supervisor/options.py

options: don't use reserved min name that overwrites builtin python min function

---

.travis.yml

[Travis are now recommending removing __sudo__](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)

Travis CI: 'sudo' is no longer required by Travis

---

supervisor/tests/test_xmlrpc.py
supervisor/xmlrpc.py

Method on parent class ( xmlrpclib.Transport.close ) expect connection to be
self._connection[1], but SupervisorTransport use self.connection for the
socket. Implement SupervisorTransport.close which uses self.connection.
Fixes #1184

xmlrpc: properly close connection on SupervisorTransport.close

---

supervisor/medusa/http_server.py

Fixes #1178 which says that a ___RuntimeError___ is raised when the dictionary size changes during iteration.  This change freezes dict.values() into a list before the loop begins so that the list will not change during iteration. 🎄

Freezing zombie channels into a list avoids RuntimeError

---

supervisor/process.py
supervisor/tests/test_process.py

- Resolves https://github.com/Supervisor/supervisor/issues/1043
- If the system clock is set to an earlier time after a process is started but before it has entered the RUNNING state, supervisorctl start <process_name> can hang for a very long time waiting for the current system time to become greater than self.laststart + self.config.startsecs, depending on how far backward the system time has moved.
- This pull request resolves the issue above and also attempts to address a couple other potential issues in process.py with system time moving backward.
- Also added related unit tests

 [process.py] Handle scenario where system clock rolls backward

---

supervisor/tests/test_end_to_end.py

https://travis-ci.org/Supervisor/supervisor/jobs/516836395#L260-L269
```
=============================== warnings summary ===============================
supervisor/tests/test_end_to_end.py:74
/home/travis/build/Supervisor/supervisor/supervisor/tests/test_end_to_end.py:74: DeprecationWarning: invalid escape sequence \s
supervisorctl.expect('test_öäü\s+RUNNING', timeout=30)
supervisor/tests/test_end_to_end.py:126
/home/travis/build/Supervisor/supervisor/supervisor/tests/test_end_to_end.py:126: DeprecationWarning: invalid escape sequence \s
supervisorctl.expect('cat\s+in use\s+auto', timeout=30)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Fix Pytest DeprecationWarning: invalid escape sequence \s

---

supervisor/options.py

Ensure main log rotation can be disabled the same way as child logs

---

.gitignore
supervisor/http_client.py
supervisor/supervisorctl.py
supervisor/tests/fixtures/issue-1231.conf
supervisor/tests/fixtures/test_1231.py
supervisor/tests/test_end_to_end.py

I've added a warning in the `tailf` command, and also changed the exception raised on `UnicodeEncodeError` to have a more informative message. A couple of related new end-to-end tests have been added and on my Ubuntu system, all tests pass with `tox` on all configured platforms.

Initial cut for fix of issue #1231

---

supervisor/supervisorctl.py

The bug was that when the channel was explicitly specified, it always
evaluated to stderr, i.e. supervisorctl tail foo stdout and
supervisorctl tail foo stderr were both showing stderr.
That is because we should not use is for such comparisons:
these two are different objects.
If curious, read more here: https://stackoverflow.com/questions/1504717/
This just changes the tail command to use == for comparing the two objects.

Fix tail bug

---

.travis.yml
supervisor/medusa/util.py
tox.ini

fix #1257 
the html module is missing in python 2 and I don't think is worth using cgi only for 3.8+ so I opted for cgi on python 2 and html for python 3+

Use html.escape for python >= 3.4

---

.gitignore
supervisor/loggers.py
supervisor/tests/test_loggers.py

All tests passing on Python2 and Python3.

Alternative approach to addressing #1282

---

supervisor/http.py
supervisor/tests/test_http.py

When supervisord behind nginx, `/logtail/PROGRAM` does not produce
log text because nginx proxy buffering is enabled by default:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
And I don't want tell everyone howto configure `proxy_buffering off;`,
so better let supervisord set http header X-Accel-Buffering to `no`.

Tell reverse proxy server to disable proxy buffering

---

supervisor/supervisorctl.py

> supervisorctl tail -f worker | grep something
crashes with error ```NoneType object has no attribute 'lower' ```

Fix error NoneType object has no attribute 'lower'

---

docs/configuration.rst
docs/running.rst
supervisor/options.py
supervisor/skel/sample.conf
supervisor/supervisord.py
supervisor/tests/base.py
supervisor/tests/test_options.py
supervisor/tests/test_supervisord.py

Added a new flag to disable logging to stdout for non daemonized instances. This is of use in a dockerized env where filebeat is being used to pump log files (including supervisord) to stdout in a standard format. Without this flag there are duplicated log entries written to stdout.
Closes #661

Flag to disable stdout logging for non daemonized instances

---

docs/configuration.rst

The code in `options.py` is as follow:
```        here = os.path.dirname(os.path.dirname(sys.argv[0]))
searchpaths = [os.path.join(here, 'etc', 'supervisord.conf'),
os.path.join(here, 'supervisord.conf'),
'supervisord.conf',
'etc/supervisord.conf',
'/etc/supervisord.conf',
'/etc/supervisor/supervisord.conf',
]
```

Fix order of search path for supervisord.conf in documentation

---

docs/logging.rst
supervisor/options.py

When the options `stdout_logfile` or `stderr_logfile` are set to
"syslog", the children are logging to the syslog service,
but the daemon is still logging to a file.
By letting the possibility to set the value for `logfile` to
"syslog", we can have the same behavior for the daemon.

Let the supervisord daemon log to syslog.

---

docs/plugins.rst

Django-supervisor is abandoned and archived https://github.com/rfk/django-supervisor. Removing it from the list of third party plugins.

Remove django-supervisor project

---

docs/configuration.rst
docs/subprocess.rst

This is in response to github issues raised about configuring backoff
delay. This change just highlights that there is an increasing delay
between retries because it wasn't immediately obvious that it is
happening. Also the connection to startsecs / startretries was unclear.

Document BACKOFF and its delay mechanism

---

docs/conf.py

Hi,
I got slightly confused when I noticed that building the documentation triggered a test run.
This reverts part of 674109eadc61943c593044d1375a0e8f159ae2ed which added the call to `setup.py test`, let me know if I missed something important but I don't see any reason to keep this weird behaviour.

Stop running tests when building the documentation

---

setup.py

Hi,
I am adding it because `pkg_resource` is used by several installed files.
Initially reported in https://bugs.gentoo.org/813300 (where it appeared that the package didn't require setuptools at runtime).

setup.py: add setuptools to install_requires

---

supervisor/process.py

The change will update the process state before event.notify so event handlers can get the latest process state.

#1457 update process state before notify events

---

supervisor/options.py

the Supervisor identifier may have been set in the command line and not in the configuration file.
the last line of ServerOptions.realize systematically overwrites the self.identifier by the value from the configuration file (that may be the default one 'supervisor').
if the identifier was set in the configuration file, the self.identifier was already updated.
so there's no point keeping this line.

identifier set in command line overwritten by default value

---

supervisor/options.py

Hi. Thanks for allowing the user to have a default `supervisord.conf` file, which allows us to reduce the command line clutter of the supervisor* executables. It's very convenient!
However, it is a little perilous because the user doesn't know which default file was chosen, since there are 6 options for default files. e.g., if I'm accustomed to using the lowest-priority default file, and somebody adds a higher-priority default file to my filesystem without telling me, it could ruin my day.
Here's a MR which simply tells the user which default config file is chosen, if the `-c` option is excluded. I'm not sure if the developers prefer to use `self.stdout.write` here, or something else. I'm open to suggestion.
Thanks!
cf:
https://github.com/Supervisor/supervisor/blob/master/supervisor/option …

Tell user which default config file was chosen

---

supervisor/web.py

IMO the problem is caused by the response body being generated as Unicode rather than bytes. Here is the proposed fix. There are a couple of other cases of `as_string()` in `web.py` which could also potentially be switched over, as we should generally be always passing bytes around. But I haven't implemented those changes, as they're not part of the bug report.

First cut at fix for #1273.

---

supervisor/process.py

added log severity based on the exit status of a process.
What I did
Supervisord logs all process exit status with INFO log level.
Change to log a process exit status with different severities/
Here is guidline
INFO: for graceful exits
WARN: SIGTERM or SIGKILLfor planned but non-graceful exits
CRIT: for any unplanned and non-graceful exit of processes
How I did it
modified finish() in process.py to check the exit status and provide a proper log level.
How to verify it
Here are some outputs
UT: # docker stop pmon
root@sonic:/home/admin# show logging supervisord | grep 'stopped|exited'
Nov 18 18:55:15.179829 sonic INFO pmon#supervisord 2020-11-18 18:54:38,765 INFO stopped: syseepromd (exit status 0)
Nov 18 18:55:15.179909 sonic INFO pmon#supervisord 2020-11-18 18:54:38,819 INFO stopped: …

Enhancement on supervisord log severity on process exit status

---

supervisor/tests/base.py
supervisor/tests/test_http.py
supervisor/tests/test_options.py

`tempfile.mktemp()` is deprecated since Python version 2.3. https://docs.python.org/2/library/tempfile.html#tempfile.mktemp

Fix use of deprecated tempfile.mktemp() in tests

---

docs/api.rst

Seems like the documentation for [getAllConfigInfo](https://github.com/Supervisor/supervisor/blob/8b83afdac70f140787fdb160d930f824a1f90a33/supervisor/rpcinterface.py#L558) is missing.

docs(api): add `getAllConfigInfo`

---

setup.py

When [Renovate bot](https://docs.renovatebot.com/) creates an automated pull request to update supervisord, it can automatically include the link to changelog so it's easier to find out what changed.
The URL name has to be one of: 'changelog', 'change log', 'changes', 'release notes', 'news', "what's new" (case insensitive). Source: https://github.com/renovatebot/renovate/blob/c3a87b687ed44a1a100e0e4f91b81e22b7c32482/lib/modules/datasource/pypi/index.ts#L130-L140

Add changelog URL to package metadata

---

docs/configuration.rst
docs/events.rst
setup.py
supervisor/confecho.py
supervisor/options.py
supervisor/resources.py
supervisor/tests/test_end_to_end.py

This reduces the installation footprint and potential memory implications from merely importing it
On Python 3.8+ no dependencies are required

Replace runtime dependency on setuptools with modern libraries

---

setup.py

Miminal current python3 requirement is 3.4 so this case can't occur.

Remove python3.3 case

---

supervisor/http_client.py

rdflib.net is now owned by a domain squatter that relays to a gambling site.

rdflib.net is now rdflib.dev

---

supervisor/supervisord.py

We found a problem of high CPU usage of the supervisor. We believe it's same reason for #807 . This problem is caused by continuous polling of a wrong fd in the main loop of the supervisor. Busy polling leads to a CPU usage close to 100%. (We can confirm this problem through the strace tool)
This issue can be reproduced by:
1. Continuously initiate arbitrary requests to supervisor through supervisorctl
2. After the socket fd is closed, trigger the supervisor's subprocess to rotate the log (or reopen the file)
3. If the above steps are completed within a single main loop of the supervisor, the problem can be triggered
The reason for the problem is that supervisor relies on using _ignore_invalid() in the main loop to close fds. This method has a flaw that if fd is reused before …

Fix high cpu usage caused by fd leak

---

docs/events.rst

Process log events (from both stdout and stderr) have channel
information in their payload. The docs have been updated to reflect
this.

Add missing channel field to process log event docs

---

supervisor/tests/test_process.py

Python 3.13 added a [`__firstlineno__`](https://docs.python.org/3/reference/datamodel.html#type.__firstlineno__) attribute to classes whose value is an int, so the approach taken by
`SubprocessTests.test_getProcessStateDescription` to test only actual states no longer works.  Exclude all attributes starting with `__` instead.

Fix tests on Python 3.13

---

supervisor/tests/test_socket_manager.py

Hi,
This is basically reapplying 0ad4db8e1411 which was removed in 49b74cafb6e7.
Without this patch, we got:
```
platform linux -- Python 3.10.14[pypy-7.3.17-final], pytest-8.3.4, pluggy-1.5.0
[…]
FAILED supervisor/tests/test_socket_manager.py::ProxyTest::test_on_delete - AssertionError: False is not true
FAILED supervisor/tests/test_socket_manager.py::SocketManagerTest::test_logging - AssertionError: 1 != 2
FAILED supervisor/tests/test_socket_manager.py::SocketManagerTest::test_socket_lifecycle - AssertionError: True is not false
FAILED supervisor/tests/test_socket_manager.py::SocketManagerTest::test_tcp_w_hostname - OSError: [Errno 98] Address already in use
FAILED supervisor/tests/test_socket_manager.py::SocketManagerTest::test_tcp_w_ip - OSError: [Errno 98] Address already in use
``` …

tests: fix test_socket_manager.py with PyPy
